name = "TermoQuimica"
uuid = "7a098a08-e70e-483f-ae9c-35bef3462704"
authors = ["Emilio Alvizo Vel√°zquez"]
version = "0.1.0"

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
NLsolve = "4.5.1"
PolynomialRoots = "1.0.0"
Unitful = "1.5"
julia = "1.5"

[targets]
test = ["Test"]